# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/audit.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/audit.proto\x12\x05\x61udit\"\x07\n\x05\x45mpty\"\xa6\x01\n\x17RecordAuditEventRequest\x12\x15\n\ractor_user_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61\x63tor_email\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x04 \x01(\t\x12\x11\n\tentity_id\x18\x05 \x01(\t\x12\x13\n\x0b\x62\x65\x66ore_json\x18\x06 \x01(\t\x12\x12\n\nafter_json\x18\x07 \x01(\t\"\xb8\x01\n\nAuditEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x15\n\ractor_user_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x61\x63tor_email\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x06 \x01(\t\x12\x11\n\tentity_id\x18\x07 \x01(\t\x12\x13\n\x0b\x62\x65\x66ore_json\x18\x08 \x01(\t\x12\x12\n\nafter_json\x18\t \x01(\t\"_\n\x16ListAuditEventsRequest\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\"3\n\x0e\x41uditEventList\x12!\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x11.audit.AuditEvent2\x99\x01\n\x0c\x41uditService\x12@\n\x10RecordAuditEvent\x12\x1e.audit.RecordAuditEventRequest\x1a\x0c.audit.Empty\x12G\n\x0fListAuditEvents\x12\x1d.audit.ListAuditEventsRequest\x1a\x15.audit.AuditEventListB\x14\xaa\x02\x11\x41uditService.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021AuditService.Grpc'
  _globals['_EMPTY']._serialized_start=29
  _globals['_EMPTY']._serialized_end=36
  _globals['_RECORDAUDITEVENTREQUEST']._serialized_start=39
  _globals['_RECORDAUDITEVENTREQUEST']._serialized_end=205
  _globals['_AUDITEVENT']._serialized_start=208
  _globals['_AUDITEVENT']._serialized_end=392
  _globals['_LISTAUDITEVENTSREQUEST']._serialized_start=394
  _globals['_LISTAUDITEVENTSREQUEST']._serialized_end=489
  _globals['_AUDITEVENTLIST']._serialized_start=491
  _globals['_AUDITEVENTLIST']._serialized_end=542
  _globals['_AUDITSERVICE']._serialized_start=545
  _globals['_AUDITSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
