# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/change.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/change.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/change.proto\x12\x06\x63hange\"\x07\n\x05\x45mpty\"\x1d\n\x0f\x43hangeIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"M\n\x13\x43hangeActionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\ractor_user_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x61\x63tor_email\x18\x03 \x01(\t\"\x88\x01\n\x13\x43reateChangeRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nrisk_level\x18\x03 \x01(\t\x12\r\n\x05\x63i_id\x18\x04 \x01(\x05\x12\x15\n\ractor_user_id\x18\x05 \x01(\x05\x12\x13\n\x0b\x61\x63tor_email\x18\x06 \x01(\t\"s\n\x0e\x43hangeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\nrisk_level\x18\x05 \x01(\t\x12\r\n\x05\x63i_id\x18\x06 \x01(\x05\"5\n\nChangeList\x12\'\n\x07\x63hanges\x18\x01 \x03(\x0b\x32\x16.change.ChangeResponse\"\x90\x01\n\x14\x43hangeWithCIResponse\x12&\n\x06\x63hange\x18\x01 \x01(\x0b\x32\x16.change.ChangeResponse\x12\x0f\n\x07\x63i_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63i_environment\x18\x03 \x01(\t\x12\x12\n\nowner_name\x18\x04 \x01(\t\x12\x13\n\x0bowner_email\x18\x05 \x01(\t2\xd4\x02\n\rChangeService\x12\x43\n\x0c\x43reateChange\x12\x1b.change.CreateChangeRequest\x1a\x16.change.ChangeResponse\x12<\n\tGetChange\x12\x17.change.ChangeIdRequest\x1a\x16.change.ChangeResponse\x12\x30\n\x0bListChanges\x12\r.change.Empty\x1a\x12.change.ChangeList\x12\x44\n\rApproveChange\x12\x1b.change.ChangeActionRequest\x1a\x16.change.ChangeResponse\x12H\n\x0fGetChangeWithCI\x12\x17.change.ChangeIdRequest\x1a\x1c.change.ChangeWithCIResponseB\x15\xaa\x02\x12\x43hangeService.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.change_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022ChangeService.Grpc'
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_CHANGEIDREQUEST']._serialized_start=40
  _globals['_CHANGEIDREQUEST']._serialized_end=69
  _globals['_CHANGEACTIONREQUEST']._serialized_start=71
  _globals['_CHANGEACTIONREQUEST']._serialized_end=148
  _globals['_CREATECHANGEREQUEST']._serialized_start=151
  _globals['_CREATECHANGEREQUEST']._serialized_end=287
  _globals['_CHANGERESPONSE']._serialized_start=289
  _globals['_CHANGERESPONSE']._serialized_end=404
  _globals['_CHANGELIST']._serialized_start=406
  _globals['_CHANGELIST']._serialized_end=459
  _globals['_CHANGEWITHCIRESPONSE']._serialized_start=462
  _globals['_CHANGEWITHCIRESPONSE']._serialized_end=606
  _globals['_CHANGESERVICE']._serialized_start=609
  _globals['_CHANGESERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
