# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import change_pb2 as protos_dot_change__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/change_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChangeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChange = channel.unary_unary(
                '/change.ChangeService/CreateChange',
                request_serializer=protos_dot_change__pb2.CreateChangeRequest.SerializeToString,
                response_deserializer=protos_dot_change__pb2.ChangeResponse.FromString,
                _registered_method=True)
        self.GetChange = channel.unary_unary(
                '/change.ChangeService/GetChange',
                request_serializer=protos_dot_change__pb2.ChangeIdRequest.SerializeToString,
                response_deserializer=protos_dot_change__pb2.ChangeResponse.FromString,
                _registered_method=True)
        self.ListChanges = channel.unary_unary(
                '/change.ChangeService/ListChanges',
                request_serializer=protos_dot_change__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_change__pb2.ChangeList.FromString,
                _registered_method=True)
        self.ApproveChange = channel.unary_unary(
                '/change.ChangeService/ApproveChange',
                request_serializer=protos_dot_change__pb2.ChangeActionRequest.SerializeToString,
                response_deserializer=protos_dot_change__pb2.ChangeResponse.FromString,
                _registered_method=True)
        self.GetChangeWithCI = channel.unary_unary(
                '/change.ChangeService/GetChangeWithCI',
                request_serializer=protos_dot_change__pb2.ChangeIdRequest.SerializeToString,
                response_deserializer=protos_dot_change__pb2.ChangeWithCIResponse.FromString,
                _registered_method=True)


class ChangeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangeWithCI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChange': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChange,
                    request_deserializer=protos_dot_change__pb2.CreateChangeRequest.FromString,
                    response_serializer=protos_dot_change__pb2.ChangeResponse.SerializeToString,
            ),
            'GetChange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChange,
                    request_deserializer=protos_dot_change__pb2.ChangeIdRequest.FromString,
                    response_serializer=protos_dot_change__pb2.ChangeResponse.SerializeToString,
            ),
            'ListChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChanges,
                    request_deserializer=protos_dot_change__pb2.Empty.FromString,
                    response_serializer=protos_dot_change__pb2.ChangeList.SerializeToString,
            ),
            'ApproveChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveChange,
                    request_deserializer=protos_dot_change__pb2.ChangeActionRequest.FromString,
                    response_serializer=protos_dot_change__pb2.ChangeResponse.SerializeToString,
            ),
            'GetChangeWithCI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangeWithCI,
                    request_deserializer=protos_dot_change__pb2.ChangeIdRequest.FromString,
                    response_serializer=protos_dot_change__pb2.ChangeWithCIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'change.ChangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('change.ChangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChangeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/change.ChangeService/CreateChange',
            protos_dot_change__pb2.CreateChangeRequest.SerializeToString,
            protos_dot_change__pb2.ChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/change.ChangeService/GetChange',
            protos_dot_change__pb2.ChangeIdRequest.SerializeToString,
            protos_dot_change__pb2.ChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/change.ChangeService/ListChanges',
            protos_dot_change__pb2.Empty.SerializeToString,
            protos_dot_change__pb2.ChangeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/change.ChangeService/ApproveChange',
            protos_dot_change__pb2.ChangeActionRequest.SerializeToString,
            protos_dot_change__pb2.ChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangeWithCI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/change.ChangeService/GetChangeWithCI',
            protos_dot_change__pb2.ChangeIdRequest.SerializeToString,
            protos_dot_change__pb2.ChangeWithCIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
