syntax = "proto3";
option csharp_namespace = "Cmdb.Grpc";

package cmdb;

service CmdbService {
    rpc CreateCI (CreateCIRequest) returns (CIResponse);
    rpc GetCI (CIIdRequest) returns (CIResponse);
    rpc ListCIs (Empty) returns (CIList);
    rpc CreateRelationship (CreateRelationshipRequest) returns (RelationshipResponse);
    rpc GetRelatedCIs (CIIdRequest) returns (CIList);
    rpc GetCIWithOwner (CIIdRequest) returns (CIWithOwnerResponse);
    rpc UpdateCI (UpdateCIRequest) returns (CIResponse);
    rpc DeleteCI (CIIdRequest) returns (Empty);

}

message Empty {}

message CIIdRequest {
    int32 id = 1;
}

message CreateCIRequest {
    string name = 1;
    string ci_type = 2;
    string environment = 3;
    optional int32 owner_team_id = 4;
    optional int32 owner_user_id = 5;
}

message UpdateCIRequest {
    int32 id = 1;
    string name = 2;
    string ci_type = 3;
    string environment = 4;
    optional int32 owner_team_id = 5;
    optional int32 owner_user_id = 6;
}

message CIResponse {
    int32 id = 1;
    string name = 2;
    string ci_type = 3;
    string environment = 4;
    optional int32 owner_team_id = 5;
    optional int32 owner_user_id = 6;
}

message CIList {
    repeated CIResponse cis = 1;
}

message CreateRelationshipRequest {
    int32 source_ci_id = 1;
    int32 target_ci_id = 2;
    string relationship_type = 3;
}

message RelationshipResponse {
    int32 id = 1;
    int32 source_ci_id = 2;
    int32 target_ci_id = 3;
    string relationship_type = 4;
}

message CIWithOwnerResponse {
    CIResponse ci = 1;
    string owner_name = 2;
    string owner_email = 3;
}