# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import incident_pb2 as protos_dot_incident__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/incident_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IncidentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateIncident = channel.unary_unary(
                '/incident.IncidentService/CreateIncident',
                request_serializer=protos_dot_incident__pb2.CreateIncidentRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.GetIncident = channel.unary_unary(
                '/incident.IncidentService/GetIncident',
                request_serializer=protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.ListIncidents = channel.unary_unary(
                '/incident.IncidentService/ListIncidents',
                request_serializer=protos_dot_incident__pb2.ListIncidentsRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.ListIncidentsResponse.FromString,
                _registered_method=True)
        self.GetIncidentWithCI = channel.unary_unary(
                '/incident.IncidentService/GetIncidentWithCI',
                request_serializer=protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentWithCIResponse.FromString,
                _registered_method=True)
        self.AddIncidentUpdate = channel.unary_unary(
                '/incident.IncidentService/AddIncidentUpdate',
                request_serializer=protos_dot_incident__pb2.AddIncidentUpdateRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.GetIncidentUpdates = channel.unary_unary(
                '/incident.IncidentService/GetIncidentUpdates',
                request_serializer=protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentUpdateList.FromString,
                _registered_method=True)
        self.AcceptSuggestedSeverity = channel.unary_unary(
                '/incident.IncidentService/AcceptSuggestedSeverity',
                request_serializer=protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.AcceptSuggestedStatus = channel.unary_unary(
                '/incident.IncidentService/AcceptSuggestedStatus',
                request_serializer=protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.UpdateIncident = channel.unary_unary(
                '/incident.IncidentService/UpdateIncident',
                request_serializer=protos_dot_incident__pb2.UpdateIncidentRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.UpdateIncidentStatus = channel.unary_unary(
                '/incident.IncidentService/UpdateIncidentStatus',
                request_serializer=protos_dot_incident__pb2.UpdateIncidentStatusRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.UpdateIncidentSeverity = channel.unary_unary(
                '/incident.IncidentService/UpdateIncidentSeverity',
                request_serializer=protos_dot_incident__pb2.UpdateIncidentSeverityRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.AssignIncident = channel.unary_unary(
                '/incident.IncidentService/AssignIncident',
                request_serializer=protos_dot_incident__pb2.AssignIncidentRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentResponse.FromString,
                _registered_method=True)
        self.DeleteIncident = channel.unary_unary(
                '/incident.IncidentService/DeleteIncident',
                request_serializer=protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.Empty.FromString,
                _registered_method=True)
        self.LinkChange = channel.unary_unary(
                '/incident.IncidentService/LinkChange',
                request_serializer=protos_dot_incident__pb2.LinkChangeRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.Empty.FromString,
                _registered_method=True)
        self.UnlinkChange = channel.unary_unary(
                '/incident.IncidentService/UnlinkChange',
                request_serializer=protos_dot_incident__pb2.LinkChangeRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLinkedChangeIds = channel.unary_unary(
                '/incident.IncidentService/GetLinkedChangeIds',
                request_serializer=protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.ChangeIdList.FromString,
                _registered_method=True)
        self.GetIncidentIdsForChange = channel.unary_unary(
                '/incident.IncidentService/GetIncidentIdsForChange',
                request_serializer=protos_dot_incident__pb2.ChangeIdRequest.SerializeToString,
                response_deserializer=protos_dot_incident__pb2.IncidentIdList.FromString,
                _registered_method=True)


class IncidentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIncidents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncidentWithCI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIncidentUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncidentUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptSuggestedSeverity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptSuggestedStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIncidentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIncidentSeverity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkedChangeIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncidentIdsForChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IncidentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIncident,
                    request_deserializer=protos_dot_incident__pb2.CreateIncidentRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'GetIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncident,
                    request_deserializer=protos_dot_incident__pb2.IncidentIdRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'ListIncidents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIncidents,
                    request_deserializer=protos_dot_incident__pb2.ListIncidentsRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.ListIncidentsResponse.SerializeToString,
            ),
            'GetIncidentWithCI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidentWithCI,
                    request_deserializer=protos_dot_incident__pb2.IncidentIdRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentWithCIResponse.SerializeToString,
            ),
            'AddIncidentUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIncidentUpdate,
                    request_deserializer=protos_dot_incident__pb2.AddIncidentUpdateRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'GetIncidentUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidentUpdates,
                    request_deserializer=protos_dot_incident__pb2.IncidentIdRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentUpdateList.SerializeToString,
            ),
            'AcceptSuggestedSeverity': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptSuggestedSeverity,
                    request_deserializer=protos_dot_incident__pb2.IncidentActionRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'AcceptSuggestedStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptSuggestedStatus,
                    request_deserializer=protos_dot_incident__pb2.IncidentActionRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'UpdateIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIncident,
                    request_deserializer=protos_dot_incident__pb2.UpdateIncidentRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'UpdateIncidentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIncidentStatus,
                    request_deserializer=protos_dot_incident__pb2.UpdateIncidentStatusRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'UpdateIncidentSeverity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIncidentSeverity,
                    request_deserializer=protos_dot_incident__pb2.UpdateIncidentSeverityRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'AssignIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignIncident,
                    request_deserializer=protos_dot_incident__pb2.AssignIncidentRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentResponse.SerializeToString,
            ),
            'DeleteIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIncident,
                    request_deserializer=protos_dot_incident__pb2.IncidentActionRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.Empty.SerializeToString,
            ),
            'LinkChange': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkChange,
                    request_deserializer=protos_dot_incident__pb2.LinkChangeRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.Empty.SerializeToString,
            ),
            'UnlinkChange': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkChange,
                    request_deserializer=protos_dot_incident__pb2.LinkChangeRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.Empty.SerializeToString,
            ),
            'GetLinkedChangeIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinkedChangeIds,
                    request_deserializer=protos_dot_incident__pb2.IncidentIdRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.ChangeIdList.SerializeToString,
            ),
            'GetIncidentIdsForChange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidentIdsForChange,
                    request_deserializer=protos_dot_incident__pb2.ChangeIdRequest.FromString,
                    response_serializer=protos_dot_incident__pb2.IncidentIdList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'incident.IncidentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('incident.IncidentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IncidentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/CreateIncident',
            protos_dot_incident__pb2.CreateIncidentRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/GetIncident',
            protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/ListIncidents',
            protos_dot_incident__pb2.ListIncidentsRequest.SerializeToString,
            protos_dot_incident__pb2.ListIncidentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncidentWithCI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/GetIncidentWithCI',
            protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentWithCIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddIncidentUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/AddIncidentUpdate',
            protos_dot_incident__pb2.AddIncidentUpdateRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncidentUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/GetIncidentUpdates',
            protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentUpdateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptSuggestedSeverity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/AcceptSuggestedSeverity',
            protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptSuggestedStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/AcceptSuggestedStatus',
            protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/UpdateIncident',
            protos_dot_incident__pb2.UpdateIncidentRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIncidentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/UpdateIncidentStatus',
            protos_dot_incident__pb2.UpdateIncidentStatusRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIncidentSeverity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/UpdateIncidentSeverity',
            protos_dot_incident__pb2.UpdateIncidentSeverityRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/AssignIncident',
            protos_dot_incident__pb2.AssignIncidentRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/DeleteIncident',
            protos_dot_incident__pb2.IncidentActionRequest.SerializeToString,
            protos_dot_incident__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/LinkChange',
            protos_dot_incident__pb2.LinkChangeRequest.SerializeToString,
            protos_dot_incident__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/UnlinkChange',
            protos_dot_incident__pb2.LinkChangeRequest.SerializeToString,
            protos_dot_incident__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkedChangeIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/GetLinkedChangeIds',
            protos_dot_incident__pb2.IncidentIdRequest.SerializeToString,
            protos_dot_incident__pb2.ChangeIdList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncidentIdsForChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.IncidentService/GetIncidentIdsForChange',
            protos_dot_incident__pb2.ChangeIdRequest.SerializeToString,
            protos_dot_incident__pb2.IncidentIdList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
