services:
  postgres:
    image: postgres:16
    container_name: microservices-postgres
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=microservices
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    container_name: enterprise-it-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  grafana:
    image: grafana/grafana:latest
    container_name: enterprise-it-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: