apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-service
  template:
    metadata:
      labels:
        app: change-service
    spec:
      containers:
        - name: change-service
          image: change-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 50054
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CHANGESERVICE_CONNECTION_STRING
            - name: CMDB_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CMDB_SERVICE_ADDR---
apiVersion: v1
kind: Service
metadata:
  name: change-service
spec:
  selector:
    app: change-service
  ports:
    - port: 50054
      targetPort: 50054
