apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-app:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: USER_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_SERVICE_ADDR
            - name: INCIDENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: INCIDENT_SERVICE_ADDR
            - name: CMDB_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CMDB_SERVICE_ADDR
            - name: CHANGE_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CHANGE_SERVICE_ADDR
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000
