# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import cmdb_pb2 as protos_dot_cmdb__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/cmdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CmdbServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCI = channel.unary_unary(
                '/cmdb.CmdbService/CreateCI',
                request_serializer=protos_dot_cmdb__pb2.CreateCIRequest.SerializeToString,
                response_deserializer=protos_dot_cmdb__pb2.CIResponse.FromString,
                _registered_method=True)
        self.GetCI = channel.unary_unary(
                '/cmdb.CmdbService/GetCI',
                request_serializer=protos_dot_cmdb__pb2.CIIdRequest.SerializeToString,
                response_deserializer=protos_dot_cmdb__pb2.CIResponse.FromString,
                _registered_method=True)
        self.ListCIs = channel.unary_unary(
                '/cmdb.CmdbService/ListCIs',
                request_serializer=protos_dot_cmdb__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_cmdb__pb2.CIList.FromString,
                _registered_method=True)
        self.CreateRelationship = channel.unary_unary(
                '/cmdb.CmdbService/CreateRelationship',
                request_serializer=protos_dot_cmdb__pb2.CreateRelationshipRequest.SerializeToString,
                response_deserializer=protos_dot_cmdb__pb2.RelationshipResponse.FromString,
                _registered_method=True)
        self.GetRelatedCIs = channel.unary_unary(
                '/cmdb.CmdbService/GetRelatedCIs',
                request_serializer=protos_dot_cmdb__pb2.CIIdRequest.SerializeToString,
                response_deserializer=protos_dot_cmdb__pb2.CIList.FromString,
                _registered_method=True)


class CmdbServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateCI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedCIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmdbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCI': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCI,
                    request_deserializer=protos_dot_cmdb__pb2.CreateCIRequest.FromString,
                    response_serializer=protos_dot_cmdb__pb2.CIResponse.SerializeToString,
            ),
            'GetCI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCI,
                    request_deserializer=protos_dot_cmdb__pb2.CIIdRequest.FromString,
                    response_serializer=protos_dot_cmdb__pb2.CIResponse.SerializeToString,
            ),
            'ListCIs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCIs,
                    request_deserializer=protos_dot_cmdb__pb2.Empty.FromString,
                    response_serializer=protos_dot_cmdb__pb2.CIList.SerializeToString,
            ),
            'CreateRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRelationship,
                    request_deserializer=protos_dot_cmdb__pb2.CreateRelationshipRequest.FromString,
                    response_serializer=protos_dot_cmdb__pb2.RelationshipResponse.SerializeToString,
            ),
            'GetRelatedCIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedCIs,
                    request_deserializer=protos_dot_cmdb__pb2.CIIdRequest.FromString,
                    response_serializer=protos_dot_cmdb__pb2.CIList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cmdb.CmdbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cmdb.CmdbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CmdbService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmdb.CmdbService/CreateCI',
            protos_dot_cmdb__pb2.CreateCIRequest.SerializeToString,
            protos_dot_cmdb__pb2.CIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmdb.CmdbService/GetCI',
            protos_dot_cmdb__pb2.CIIdRequest.SerializeToString,
            protos_dot_cmdb__pb2.CIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmdb.CmdbService/ListCIs',
            protos_dot_cmdb__pb2.Empty.SerializeToString,
            protos_dot_cmdb__pb2.CIList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmdb.CmdbService/CreateRelationship',
            protos_dot_cmdb__pb2.CreateRelationshipRequest.SerializeToString,
            protos_dot_cmdb__pb2.RelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedCIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmdb.CmdbService/GetRelatedCIs',
            protos_dot_cmdb__pb2.CIIdRequest.SerializeToString,
            protos_dot_cmdb__pb2.CIList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
