# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/cmdb.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/cmdb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/cmdb.proto\x12\x04\x63mdb\"\x07\n\x05\x45mpty\"\x19\n\x0b\x43IIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"s\n\x0f\x43reateCIRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63i_type\x18\x02 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x01(\t\x12\x1a\n\rowner_team_id\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x10\n\x0e_owner_team_id\"z\n\nCIResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63i_type\x18\x03 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x04 \x01(\t\x12\x1a\n\rowner_team_id\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x10\n\x0e_owner_team_id\"\'\n\x06\x43IList\x12\x1d\n\x03\x63is\x18\x01 \x03(\x0b\x32\x10.cmdb.CIResponse\"b\n\x19\x43reateRelationshipRequest\x12\x14\n\x0csource_ci_id\x18\x01 \x01(\x05\x12\x14\n\x0ctarget_ci_id\x18\x02 \x01(\x05\x12\x19\n\x11relationship_type\x18\x03 \x01(\t\"i\n\x14RelationshipResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0csource_ci_id\x18\x02 \x01(\x05\x12\x14\n\x0ctarget_ci_id\x18\x03 \x01(\x05\x12\x19\n\x11relationship_type\x18\x04 \x01(\t2\x9b\x02\n\x0b\x43mdbService\x12\x33\n\x08\x43reateCI\x12\x15.cmdb.CreateCIRequest\x1a\x10.cmdb.CIResponse\x12,\n\x05GetCI\x12\x11.cmdb.CIIdRequest\x1a\x10.cmdb.CIResponse\x12$\n\x07ListCIs\x12\x0b.cmdb.Empty\x1a\x0c.cmdb.CIList\x12Q\n\x12\x43reateRelationship\x12\x1f.cmdb.CreateRelationshipRequest\x1a\x1a.cmdb.RelationshipResponse\x12\x30\n\rGetRelatedCIs\x12\x11.cmdb.CIIdRequest\x1a\x0c.cmdb.CIListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.cmdb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_CIIDREQUEST']._serialized_start=36
  _globals['_CIIDREQUEST']._serialized_end=61
  _globals['_CREATECIREQUEST']._serialized_start=63
  _globals['_CREATECIREQUEST']._serialized_end=178
  _globals['_CIRESPONSE']._serialized_start=180
  _globals['_CIRESPONSE']._serialized_end=302
  _globals['_CILIST']._serialized_start=304
  _globals['_CILIST']._serialized_end=343
  _globals['_CREATERELATIONSHIPREQUEST']._serialized_start=345
  _globals['_CREATERELATIONSHIPREQUEST']._serialized_end=443
  _globals['_RELATIONSHIPRESPONSE']._serialized_start=445
  _globals['_RELATIONSHIPRESPONSE']._serialized_end=550
  _globals['_CMDBSERVICE']._serialized_start=553
  _globals['_CMDBSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
