# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/incident.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/incident.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/incident.proto\x12\x08incident\"\x07\n\x05\x45mpty\"\x1f\n\x11IncidentIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\\\n\x15\x43reateIncidentRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\r\n\x05\x63i_id\x18\x04 \x01(\x05\"s\n\x10IncidentResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\r\n\x05\x63i_id\x18\x06 \x01(\x05\"=\n\x0cIncidentList\x12-\n\tincidents\x18\x01 \x03(\x0b\x32\x1a.incident.IncidentResponse\"\x98\x01\n\x16IncidentWithCIResponse\x12,\n\x08incident\x18\x01 \x01(\x0b\x32\x1a.incident.IncidentResponse\x12\x0f\n\x07\x63i_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63i_environment\x18\x03 \x01(\t\x12\x12\n\nowner_name\x18\x04 \x01(\t\x12\x13\n\x0bowner_email\x18\x05 \x01(\t2\xb6\x02\n\x0fIncidentService\x12M\n\x0e\x43reateIncident\x12\x1f.incident.CreateIncidentRequest\x1a\x1a.incident.IncidentResponse\x12\x46\n\x0bGetIncident\x12\x1b.incident.IncidentIdRequest\x1a\x1a.incident.IncidentResponse\x12\x38\n\rListIncidents\x12\x0f.incident.Empty\x1a\x16.incident.IncidentList\x12R\n\x11GetIncidentWithCI\x12\x1b.incident.IncidentIdRequest\x1a .incident.IncidentWithCIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.incident_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_INCIDENTIDREQUEST']._serialized_start=44
  _globals['_INCIDENTIDREQUEST']._serialized_end=75
  _globals['_CREATEINCIDENTREQUEST']._serialized_start=77
  _globals['_CREATEINCIDENTREQUEST']._serialized_end=169
  _globals['_INCIDENTRESPONSE']._serialized_start=171
  _globals['_INCIDENTRESPONSE']._serialized_end=286
  _globals['_INCIDENTLIST']._serialized_start=288
  _globals['_INCIDENTLIST']._serialized_end=349
  _globals['_INCIDENTWITHCIRESPONSE']._serialized_start=352
  _globals['_INCIDENTWITHCIRESPONSE']._serialized_end=504
  _globals['_INCIDENTSERVICE']._serialized_start=507
  _globals['_INCIDENTSERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
