# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x07\n\x05\x45mpty\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"7\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"-\n\x08UserList\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse2\xac\x01\n\x0bUserService\x12*\n\x0bGetAllUsers\x12\x0b.user.Empty\x1a\x0e.user.UserList\x12\x36\n\x0bGetUserById\x12\x13.user.UserIdRequest\x1a\x12.user.UserResponse\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_USERIDREQUEST']._serialized_start=29
  _globals['_USERIDREQUEST']._serialized_end=56
  _globals['_CREATEUSERREQUEST']._serialized_start=58
  _globals['_CREATEUSERREQUEST']._serialized_end=124
  _globals['_USERRESPONSE']._serialized_start=126
  _globals['_USERRESPONSE']._serialized_end=181
  _globals['_USERLIST']._serialized_start=183
  _globals['_USERLIST']._serialized_end=228
  _globals['_USERSERVICE']._serialized_start=231
  _globals['_USERSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
