"""add incident_updates table and au_suggested_status

Revision ID: 06480d97028c
Revises: 6d3eff1cdc7e
Create Date: 2026-08-06 12:20:32.402349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06480d97028c'
down_revision: Union[str, Sequence[str], None] = '6d3eff1cdc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incidents', sa.Column('ai_suggested_status', sa.String(), nullable=True))# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'ai_suggested_status')
    op.drop_table('incident_updates')
    # ### end Alembic commands ###
