"""add owner_user_id to configuraiton_items

Revision ID: 8e07887d7f53
Revises: cb62e8e43020
Create Date: 2026-07-24 11:27:08.101312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e07887d7f53'
down_revision: Union[str, Sequence[str], None] = 'cb62e8e43020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_items', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configuration_items', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configuration_items', type_='foreignkey')
    op.drop_column('configuration_items', 'owner_user_id')
    # ### end Alembic commands ###
