"""add cmdb tables

Revision ID: cb62e8e43020
Revises: 88f6e7083dba
Create Date: 2026-07-22 13:07:13.855004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb62e8e43020'
down_revision: Union[str, Sequence[str], None] = '88f6e7083dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ci_type', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ci_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ci_id', sa.Integer(), nullable=False),
    sa.Column('target_ci_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_ci_id'], ['configuration_items.id'], ),
    sa.ForeignKeyConstraint(['target_ci_id'], ['configuration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ci_relationships')
    op.drop_table('configuration_items')
    op.drop_table('teams')
    # ### end Alembic commands ###
