"""add ai_suggested_severity to incidents

Revision ID: 6d3eff1cdc7e
Revises: d0e225b099f6
Create Date: 2026-08-06 10:18:09.306010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3eff1cdc7e'
down_revision: Union[str, Sequence[str], None] = 'd0e225b099f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('ai_suggested_severity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'ai_suggested_severity')
    # ### end Alembic commands ###
