"""add ai_summary_status to incidents

Revision ID: d0e225b099f6
Revises: c04d79838ea0
Create Date: 2026-08-05 15:05:30.105622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e225b099f6'
down_revision: Union[str, Sequence[str], None] = 'c04d79838ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('ai_summary_status', sa.String(), server_default=sa.text("'pending'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'ai_summary_status')